services:
  send2ereader:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: send2ereader
    # Restart means, Automatic re-start the container after a shutdown unless manual stop container
    restart: unless-stopped
    # Ports means, Bind external and internal docker ports, only change the external port, not the internal port
    # Format: <External Port>:<Internal Port>
    ports:
      - "3683:3683"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3682/health" ]
      interval: 6000s
      timeout: 10s
      retries: 3
      start_period: 10s
